version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    restart: always
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      network.host: 0.0.0.0
      http.port: 9200
      ELASTIC_PASSWORD: 'elasticsearch'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    container_name: logstash
    restart: always
    hostname: logstash
    image: logstash:7.14.0
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - lsdata:/usr/share/logstash/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 9600:9600
      - 7777:7777
      - 5000:5000

volumes:
  esdata:
  lsdata:
